### ISSUE TITLE
Local Notifications

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#167]
- [x] Did you know? - prompt about a (Possibly new) feature they haven't used
 - [ ] Location popup - alert them that they're near a demo unit that is available for eval
 - [ ] ...

**Comment by finger563** [comment]
requires the https://github.com/eddyverbruggen/nativescript-local-notifications plugin

**Comment by bradmartin** [comment]
Reviewed this, we probably go with the feedback plugin as it's better suited in the app for providing this info. The local notifications plugin still has the chance of notifications being disabled which it would never show then.

This is also related to some of the DidYouKnow stuff I have for Devon with Push notifications. So that will come in as a push notification when the data is entered to our endpoint.

The location popup we probably just use a standard dialog or the feedback plugin for a bit nicer UI there.

**Comment by bradmartin** [comment]
Or another option might be the fancy alert plugin https://github.com/NathanWalker/nativescript-fancyalert @finger563 - this is probably better in the app actually so it's not missed since the feedback requires a `duration`. So things we NEED the user to know about we should block them for a second to make sure they are aware of it, things not needing to be blocked then feedback or a snackbar would be nicer UX.

**Comment by bradmartin** [comment]
Even better looking for how we present this: https://github.com/shiv19/nativescript-cfalert-dialog

**Comment by bradmartin** [comment]
Closing to clean up and lessen noise. We can isolate new features needed based on locations as needed moving into next release.
