### ISSUE TITLE
GIFs are offset to the right side of the screen

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#170]

**Comment by bradmartin** [comment]
I've fixed the plugin and submitted a PR to correct where the issue is coming from. Also pinged the author to get it published, he's usually responsive so I expect it to be published tomorrow. Until then, this part of the app will be corrected when that happens. If not published I'll make a fork and we can use it until an update is published.

**Comment by finger563** [comment]
haha @bradmartin

**Comment by bradmartin** [comment]
Waiting https://github.com/manijak/nativescript-carousel/pull/75

**Comment by finger563** [comment]
Looks like this was merged - so we should be good?

**Comment by bradmartin** [comment]
he didn't pub it but pinged him and said he would when he got home from the office. He's in Europe so should be sometime today and then all those odd alignment issues in carousel will be good 👍

**Comment by finger563** [comment]
Yay he published it :)
