### ISSUE TITLE
look into slider sensitivity / controls on carousel pages

### ISSUE THREAD

**Issue by finger563** [PushTracker/EvalApp#284]
- [ ] pushtracker settings page
- [ ] trial configuration page

**Comment by finger563** [comment]
perhaps either
 * add buttons to each side for +/-, or
 * replace with list-picker / drop-down?

**Comment by bradmartin** [comment]
I'd vote for buttons, dropdowns and list pickers are fine but slow the input process down. Especially if you select the wrong value and have to open the picker again. Then again, tapping a button 8 times to get where you want takes time so maybe that argument isn't valid in this scenario.

A fast `action` dialog might be best since it'll be platform specific and they're quick to display, unlike the dropdown which has the animation (that is what feels slow about the dropdown to me).

**Comment by bradmartin** [comment]
https://github.com/PushTracker/EvalApp/pull/297 should help with this by making sure we aren't 100% width on the sliders on carousel so it's less likely the edge touches will start sliding the carousel assuming the touch is initiated on the slider and not on the page/carousel view instance.

**Comment by bradmartin** [comment]
Closing for now, it's much more difficult now to accidentally swipe the carousel when trying to change the sliders. They have a margin left/right applied when inside a carousel.
